# Версия docker API
version: "3.7"

services:
  # database
  db:
    image: postgres:12-alpine
    # Устанавливаем каталог и создаем таблицу
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./schema.sql:/docker-entrypoint-initdb.d/init.sql
    # Переменные окружения для подключения к БД
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}

    expose:
      - 5432

    # Web-service
  app:
    build: .

    volumes:
      - .:/opt/app
    # Переменные окружения для подключения к БД
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}

    ports:
      - 8888:8888
    # Ждем пока не запуститься БД
    depends_on:
      - db

volumes:
  postgres_data:
